\input texinfo

@c %**start of header
@setfilename Maze_infp.info
@settitle Maze
@c %**end of header

@copying
This is a manual for Maze

Copyright @copyright{} 2023 dyahdeme, lavondas
@end copying

@ifnottex
@node Top
@top The Maze program. Description of work.

Краткое описание работы программы Maze и её функционала.

@titlefont{Описание программы}

В проекте реализовано приложение для генерации идеальных лабиринтов на языке программирования С++ с использованием @acronym{ООП}. @*
Логика программы реализована с использованием паттерна @acronym{MVC}.@*
Так же есть возможность возможность показать решение любого лабиринта, который сейчас изображен на экране. @*
Пользователем задаются начальная и конечная точки. @*
Маршрут, являющийся решением, отображается красной линией толщиной 2 пикселя. @*
Программа позволяет сохранять полученные лабиринты в файл в формате .txt, а так же загружать лабиринты в формате .txt @*


@titlefont{Описание функционала Maze}

@itemize @bullet
@item
Программа разработана на языке С++ стандарта C++17 с использованием компилятора g++. 
@item
Код программы находится в папке src 
@item
Сборка программы настроена с помощью Makefile со стандартным набором целей для GNU-программ: 
all, install, uninstall, clean, dvi, dist, test, gcov_report. 
Установка производится в каталог src/build
@item
Программа разработана в соответствии с принципами @acronym{ООП}
@item
Обеспечено покрытие unit-тестами модулей, связанных с генерацией лабиринта и поиска решений, с помощью библиотеки GTest
@item
Графический пользовательский интерфейс реализован на базе Qt
@end itemize
@end ifnottex


@titlepage
@title Maze Manual

@page
@vskip 0pt plus 1fill
@insertcopying
@end titlepage

@bye
